services:
  mini-lab-scheduler:
    image: ghcr.io/2025-nycu-cloud-native-team17/mini-lab-scheduler:latest
    build:
      context: ../mini-lab-scheduler
      dockerfile: Dockerfile
    container_name: mini-lab-scheduler
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: ghcr.io/2025-nycu-cloud-native-team17/mini-lab-db:latest
    build:
      context: ../mini-lab-api
      dockerfile: dockerfile.init.db
    container_name: mini-lab-mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  mini-lab-api:
    image: ghcr.io/2025-nycu-cloud-native-team17/mini-lab-api:latest
    build:
      context: ../mini-lab-api
      dockerfile: dockerfile
    container_name: mini-lab-api
    depends_on:
      - db
      - mini-lab-scheduler
    volumes:
      - /var/log/mini-lab:/var/log/mini-lab
    ports:
      - "8888:8888"
    networks:
      - app-network

  mini-lab-web:
    image: ghcr.io/2025-nycu-cloud-native-team17/mini-lab-web:dev
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: mini-lab-web
    depends_on:
      - mini-lab-api
    volumes:
      - .:/app
      - /app/node_modules   # 防止 node_modules 被 host 上覆蓋
    environment:
      - CHOKIDAR_USEPOLLING=true   # 支援即時監控變更（避免 Linux inotify 問題）
      - DANGEROUSLY_DISABLE_HOST_CHECK=true # Disable host check cypress to access
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
