# Dockerfile.cypress-font
FROM cypress/included:12.17.4

RUN rm -f /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get install -y fonts-noto-cjk curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
