name: Run Cypress Tests

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Build and Push mini-lab-web"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - "cypress/**"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services
        run: docker compose -f docker-compose.prod.yml up -d --quiet-pull

      - name: Debug service availability
        run: |
          docker ps

      - name: Wait for app
        run: |
          echo "Waiting for http://localhost:3000..."
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 > /dev/null; then
              echo "App is ready"
              exit 0
            fi
            sleep 2
          done
          echo "Timeout waiting for http://localhost:3000"
          exit 1

      - name: Pre-pull Cypress image
        run: docker pull ghcr.io/2025-nycu-cloud-native-team17/mini-lab-cypress --quiet

      - name: Run Cypress
        run: |
          docker run --rm \
            --network host \
            -e CYPRESS_baseUrl=http://localhost:3000 \
            -v ${{ github.workspace }}:/e2e \
            -v ${{ github.workspace }}/cypress/outputs/screenshots:/e2e/cypress/screenshots \
            -v ${{ github.workspace }}/cypress/outputs/videos:/e2e/cypress/videos \
            ghcr.io/2025-nycu-cloud-native-team17/mini-lab-cypress \
            npx cypress run --project /e2e

      - name: Upload Cypress Outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-outputs
          path: ./cypress/outputs
