name: Build and Push mini-lab-web

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - cypress/**
      - .github/**
      - "docker-compose.*"
      - "**/*.md"

jobs:
  build-web-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image names
        run: |
          echo "WEB_IMAGE=ghcr.io/${{ github.repository }}:latest" >> $GITHUB_ENV

      - name: Build and push web image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f dockerfile.prod \
            -t $WEB_IMAGE \
            --push .
